[package]
name = "energiatili-import"
version = "0.1.0"
authors = ["Ossi Herrala <oherrala@iki.fi>"]
license = "MIT"

[dependencies]
cookie = "0.11"
energiatili_model = { path = "../energiatili-model" }
env_logger = "0.6"
log = "0.4"
reqwest = "0.8"
serde_json = "1"
